name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk/svg-only@v2
        with:
          github_user_name: bijay085
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg
      - uses: EndBug/add-and-commit@v7
        with:
          branch: output
          message: 'Generate Snake'
